### ISSUE TITLE
update the expiry time of the member

### ISSUE THREAD

**Issue by onmpen** [salrashid123/iam_autorevoke#1]
hello, when i add a member and set the expiry time, how can i update the expiry time of the member?

**Comment by salrashid123** [comment]
unfortunately, there isn't an `update` function for the cloudidentity groups api

  https://cloud.google.com/identity/docs/reference/rest/v1/groups

and simply trying to set a new expiration time in update results in

```
Error Adding group member googleapi: Error 409: Error(4003): Cannot create membership 'user2@domain.com' in 'groups/02grqrue4gb58m7' because it already exists.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ResourceInfo",
    "description": "Error(4003): Cannot create membership 'user2@domain.com' in 'groups/02grqrue4gb58m7' because it already exists.",
    "owner": "domain:cloudidentity.googleapis.com",
    "resourceType": "cloudidentity.googleapis.com/Membership"
  }
]
```

**Comment by onmpen** [comment]
> unfortunately, there isn't an `update` function for the cloudidentity groups api
> 
> https://cloud.google.com/identity/docs/reference/rest/v1/groups
> 
> and simply trying to set a new expiration time in update results in
> 
> ```
> Error Adding group member googleapi: Error 409: Error(4003): Cannot create membership 'user2@domain.com' in 'groups/02grqrue4gb58m7' because it already exists.
> Details:
> [
>   {
>     "@type": "type.googleapis.com/google.rpc.ResourceInfo",
>     "description": "Error(4003): Cannot create membership 'user2@domain.com' in 'groups/02grqrue4gb58m7' because it already exists.",
>     "owner": "domain:cloudidentity.googleapis.com",
>     "resourceType": "cloudidentity.googleapis.com/Membership"
>   }
> ]
> ```

what about this one: https://cloud.google.com/identity/docs/how-to/manage-expirations?authuser=6#updating_the_expiration_of_a_membership

**Comment by salrashid123** [comment]
oh, ok, i dind't see that.  i'll add an update function tomorrow 
(unless you want to submit a PR sooner!)

**Comment by salrashid123** [comment]
it was relatively easy and in PR https://github.com/salrashid123/iam_autorevoke/commit/0b4364a92a789a9185bce206f9193dc184e8df66


fwiw, i used my own way to wrap GCP error responses to catch the `409 Conflict` exception on update

ref:
https://github.com/salrashid123/gcp_error_handler

**Comment by onmpen** [comment]
Thanks!

**Comment by onmpen** [comment]
Hi, the program doesn't seem to be able to extend the validity period for existing users

User is already member of group.  Extending membership durationUpdated existing Membership: groups/01t3444428t7qlz/memberships/1071845944444465920041
%!(EXTRA string=2022-04-25T00:22:35Z)

**Comment by salrashid123** [comment]
the output there indicates it was successfully updated.

Here's the end-to-end

```
$ go run main.go --groupID=02grqrue4gb58m7 --userID=user2@esodemoapp2.com --expireIn=5 --quotaProject=$PROJECT_ID
Members: user1@esodemoapp2.com
Added user2@esodemoapp2.com


$ gcloud identity groups memberships list --group-email=group1_3@esodemoapp2.com
---
name: groups/02grqrue4gb58m7/memberships/104497032270219758212
preferredMemberKey:
  id: user1@esodemoapp2.com
roles:
- name: MEMBER
---
name: groups/02grqrue4gb58m7/memberships/101638213306164197874
preferredMemberKey:
  id: user2@esodemoapp2.com
roles:
- name: MEMBER

$ go run main.go --groupID=02grqrue4gb58m7 --userID=user2@esodemoapp2.com --expireIn=10 --quotaProject=$PROJECT_ID --autoExtend
Members: user1@esodemoapp2.com
Members: user2@esodemoapp2.com
User is already member of group.  Extending membership duration
Updated existing Membership: groups/02grqrue4gb58m7/memberships/101638213306164197874
```
